name: bersatubantu
description: "BersatuBantu - Platform Kolaborasi Bantuan"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0  # Untuk custom fonts
  flutter_svg: ^2.0.9   # Jika butuh SVG
  shared_preferences: ^2.2.2  # Untuk menyimpan status onboarding
  file_picker: ^5.2.6
  provider: ^6.0.5
  crypto: ^3.0.3
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # Assets untuk logo dan ilustrasi
  assets:
    - assets/bersatubantu.png
  
  # Fonts configuration
  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/circular-std-medium-500.ttf
          weight: 500
        - asset: assets/circular-std-medium-500.ttf
          weight: 700